include: package:lints/recommended.yaml
analyzer:
  exclude:
    - example/
    - dev/
    - test/
    - test
    - dev
    - templates
linter:
  rules:
    - public_member_api_docs
formatter:
  page_width: 9999999999
