name: 'general_lib'
description: 'All in one library for help you make easy app on cross platform and support server side, inclue tcp, fetch, event emitter, websocket, and more.'
version: '0.0.56'
environment:
  sdk: '>=3.6.0 <4.0.0'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
dependencies:
  collection: '^1.19.0'
  http: '^1.2.2'
  path: '^1.9.0'
  io_universe: '^0.0.4'
  encrypt: '^5.0.3'
  stack_trace: '^1.12.0'
  mason_logger: '^0.3.1'
  yaml: '^3.1.2'
  archive: '^4.0.2'
  qr: '^3.0.2'
  zxing2: '^0.2.0'
  image: '^4.3.0'
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
repository: 'https://github.com/azkadev/general_lib'
homepage: 'https://youtube.com/@azkadev'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://youtube.com/@azkadev'
