
/// example:
/// 
/// "dz": {
///   "@type": "languageCodeDataDetail",
///   "name": "Algeria",
///   "flag": "🇩🇿",
///   "code": "DZ",
///   "dial_code": "+213"
/// },
final Map<String, Map> languageCodeJson = {
  "dz": {"@type": "languageCodeDataDetail", "name": "Algeria", "flag": "🇩🇿", "code": "DZ", "dial_code": "+213"},
  "as": {"@type": "languageCodeDataDetail", "name": "American Samoa", "flag": "🇦🇸", "code": "AS", "dial_code": "+1684"},
  "ad": {"@type": "languageCodeDataDetail", "name": "Andorra", "flag": "🇦🇩", "code": "AD", "dial_code": "+376"},
  "ao": {"@type": "languageCodeDataDetail", "name": "Angola", "flag": "🇦🇴", "code": "AO", "dial_code": "+244"},
  "ai": {"@type": "languageCodeDataDetail", "name": "Anguilla", "flag": "🇦🇮", "code": "AI", "dial_code": "+1264"},
  "aq": {"@type": "languageCodeDataDetail", "name": "Antarctica", "flag": "🇦🇶", "code": "AQ", "dial_code": "+672"},
  "ag": {"@type": "languageCodeDataDetail", "name": "Antigua and Barbuda", "flag": "🇦🇬", "code": "AG", "dial_code": "+1268"},
  "ar": {"@type": "languageCodeDataDetail", "name": "Argentina", "flag": "🇦🇷", "code": "AR", "dial_code": "+54"},
  "am": {"@type": "languageCodeDataDetail", "name": "Armenia", "flag": "🇦🇲", "code": "AM", "dial_code": "+374"},
  "aw": {"@type": "languageCodeDataDetail", "name": "Aruba", "flag": "🇦🇼", "code": "AW", "dial_code": "+297"},
  "au": {"@type": "languageCodeDataDetail", "name": "Australia", "flag": "🇦🇺", "code": "AU", "dial_code": "+61"},
  "at": {"@type": "languageCodeDataDetail", "name": "Austria", "flag": "🇦🇹", "code": "AT", "dial_code": "+43"},
  "az": {"@type": "languageCodeDataDetail", "name": "Azerbaijan", "flag": "🇦🇿", "code": "AZ", "dial_code": "+994"},
  "bs": {"@type": "languageCodeDataDetail", "name": "Bahamas", "flag": "🇧🇸", "code": "BS", "dial_code": "+1242"},
  "bh": {"@type": "languageCodeDataDetail", "name": "Bahrain", "flag": "🇧🇭", "code": "BH", "dial_code": "+973"},
  "bd": {"@type": "languageCodeDataDetail", "name": "Bangladesh", "flag": "🇧🇩", "code": "BD", "dial_code": "+880"},
  "bb": {"@type": "languageCodeDataDetail", "name": "Barbados", "flag": "🇧🇧", "code": "BB", "dial_code": "+1246"},
  "by": {"@type": "languageCodeDataDetail", "name": "Belarus", "flag": "🇧🇾", "code": "BY", "dial_code": "+375"},
  "be": {"@type": "languageCodeDataDetail", "name": "Belgium", "flag": "🇧🇪", "code": "BE", "dial_code": "+32"},
  "bz": {"@type": "languageCodeDataDetail", "name": "Belize", "flag": "🇧🇿", "code": "BZ", "dial_code": "+501"},
  "bj": {"@type": "languageCodeDataDetail", "name": "Benin", "flag": "🇧🇯", "code": "BJ", "dial_code": "+229"},
  "bm": {"@type": "languageCodeDataDetail", "name": "Bermuda", "flag": "🇧🇲", "code": "BM", "dial_code": "+1441"},
  "bt": {"@type": "languageCodeDataDetail", "name": "Bhutan", "flag": "🇧🇹", "code": "BT", "dial_code": "+975"},
  "bo": {"@type": "languageCodeDataDetail", "name": "Bolivia, Plurinational State of bolivia", "flag": "🇧🇴", "code": "BO", "dial_code": "+591"},
  "ba": {"@type": "languageCodeDataDetail", "name": "Bosnia and Herzegovina", "flag": "🇧🇦", "code": "BA", "dial_code": "+387"},
  "bw": {"@type": "languageCodeDataDetail", "name": "Botswana", "flag": "🇧🇼", "code": "BW", "dial_code": "+267"},
  "bv": {"@type": "languageCodeDataDetail", "name": "Bouvet Island", "flag": "🇧🇻", "code": "BV", "dial_code": "+47"},
  "br": {"@type": "languageCodeDataDetail", "name": "Brazil", "flag": "🇧🇷", "code": "BR", "dial_code": "+55"},
  "io": {"@type": "languageCodeDataDetail", "name": "British Indian Ocean Territory", "flag": "🇮🇴", "code": "IO", "dial_code": "+246"},
  "bn": {"@type": "languageCodeDataDetail", "name": "Brunei Darussalam", "flag": "🇧🇳", "code": "BN", "dial_code": "+673"},
  "bg": {"@type": "languageCodeDataDetail", "name": "Bulgaria", "flag": "🇧🇬", "code": "BG", "dial_code": "+359"},
  "bf": {"@type": "languageCodeDataDetail", "name": "Burkina Faso", "flag": "🇧🇫", "code": "BF", "dial_code": "+226"},
  "bi": {"@type": "languageCodeDataDetail", "name": "Burundi", "flag": "🇧🇮", "code": "BI", "dial_code": "+257"},
  "kh": {"@type": "languageCodeDataDetail", "name": "Cambodia", "flag": "🇰🇭", "code": "KH", "dial_code": "+855"},
  "cm": {"@type": "languageCodeDataDetail", "name": "Cameroon", "flag": "🇨🇲", "code": "CM", "dial_code": "+237"},
  "ca": {"@type": "languageCodeDataDetail", "name": "Canada", "flag": "🇨🇦", "code": "CA", "dial_code": "+1"},
  "cv": {"@type": "languageCodeDataDetail", "name": "Cape Verde", "flag": "🇨🇻", "code": "CV", "dial_code": "+238"},
  "ky": {"@type": "languageCodeDataDetail", "name": "Cayman Islands", "flag": "🇰🇾", "code": "KY", "dial_code": "+345"},
  "cf": {"@type": "languageCodeDataDetail", "name": "Central African Republic", "flag": "🇨🇫", "code": "CF", "dial_code": "+236"},
  "td": {"@type": "languageCodeDataDetail", "name": "Chad", "flag": "🇹🇩", "code": "TD", "dial_code": "+235"},
  "cl": {"@type": "languageCodeDataDetail", "name": "Chile", "flag": "🇨🇱", "code": "CL", "dial_code": "+56"},
  "cn": {"@type": "languageCodeDataDetail", "name": "China", "flag": "🇨🇳", "code": "CN", "dial_code": "+86"},
  "cx": {"@type": "languageCodeDataDetail", "name": "Christmas Island", "flag": "🇨🇽", "code": "CX", "dial_code": "+61"},
  "cc": {"@type": "languageCodeDataDetail", "name": "Cocos (Keeling) Islands", "flag": "🇨🇨", "code": "CC", "dial_code": "+61"},
  "co": {"@type": "languageCodeDataDetail", "name": "Colombia", "flag": "🇨🇴", "code": "CO", "dial_code": "+57"},
  "km": {"@type": "languageCodeDataDetail", "name": "Comoros", "flag": "🇰🇲", "code": "KM", "dial_code": "+269"},
  "cg": {"@type": "languageCodeDataDetail", "name": "Congo", "flag": "🇨🇬", "code": "CG", "dial_code": "+242"},
  "cd": {"@type": "languageCodeDataDetail", "name": "Congo, The Democratic Republic of the Congo", "flag": "🇨🇩", "code": "CD", "dial_code": "+243"},
  "ck": {"@type": "languageCodeDataDetail", "name": "Cook Islands", "flag": "🇨🇰", "code": "CK", "dial_code": "+682"},
  "cr": {"@type": "languageCodeDataDetail", "name": "Costa Rica", "flag": "🇨🇷", "code": "CR", "dial_code": "+506"},
  "ci": {"@type": "languageCodeDataDetail", "name": "Cote d'Ivoire", "flag": "🇨🇮", "code": "CI", "dial_code": "+225"},
  "hr": {"@type": "languageCodeDataDetail", "name": "Croatia", "flag": "🇭🇷", "code": "HR", "dial_code": "+385"},
  "cu": {"@type": "languageCodeDataDetail", "name": "Cuba", "flag": "🇨🇺", "code": "CU", "dial_code": "+53"},
  "cy": {"@type": "languageCodeDataDetail", "name": "Cyprus", "flag": "🇨🇾", "code": "CY", "dial_code": "+357"},
  "cz": {"@type": "languageCodeDataDetail", "name": "Czech Republic", "flag": "🇨🇿", "code": "CZ", "dial_code": "+420"},
  "dk": {"@type": "languageCodeDataDetail", "name": "Denmark", "flag": "🇩🇰", "code": "DK", "dial_code": "+45"},
  "dj": {"@type": "languageCodeDataDetail", "name": "Djibouti", "flag": "🇩🇯", "code": "DJ", "dial_code": "+253"},
  "dm": {"@type": "languageCodeDataDetail", "name": "Dominica", "flag": "🇩🇲", "code": "DM", "dial_code": "+1767"},
  "do": {"@type": "languageCodeDataDetail", "name": "Dominican Republic", "flag": "🇩🇴", "code": "DO", "dial_code": "+1849"},
  "ec": {"@type": "languageCodeDataDetail", "name": "Ecuador", "flag": "🇪🇨", "code": "EC", "dial_code": "+593"},
  "eg": {"@type": "languageCodeDataDetail", "name": "Egypt", "flag": "🇪🇬", "code": "EG", "dial_code": "+20"},
  "sv": {"@type": "languageCodeDataDetail", "name": "El Salvador", "flag": "🇸🇻", "code": "SV", "dial_code": "+503"},
  "gq": {"@type": "languageCodeDataDetail", "name": "Equatorial Guinea", "flag": "🇬🇶", "code": "GQ", "dial_code": "+240"},
  "en": {"@type": "languageCodeDataDetail", "name": "Inggris", "flag": "🇺🇸", "code": "EN", "dial_code": "+1"},
  "er": {"@type": "languageCodeDataDetail", "name": "Eritrea", "flag": "🇪🇷", "code": "ER", "dial_code": "+291"},
  "ee": {"@type": "languageCodeDataDetail", "name": "Estonia", "flag": "🇪🇪", "code": "EE", "dial_code": "+372"},
  "et": {"@type": "languageCodeDataDetail", "name": "Ethiopia", "flag": "🇪🇹", "code": "ET", "dial_code": "+251"},
  "fk": {"@type": "languageCodeDataDetail", "name": "Falkland Islands (Malvinas)", "flag": "🇫🇰", "code": "FK", "dial_code": "+500"},
  "fo": {"@type": "languageCodeDataDetail", "name": "Faroe Islands", "flag": "🇫🇴", "code": "FO", "dial_code": "+298"},
  "fj": {"@type": "languageCodeDataDetail", "name": "Fiji", "flag": "🇫🇯", "code": "FJ", "dial_code": "+679"},
  "fi": {"@type": "languageCodeDataDetail", "name": "Finland", "flag": "🇫🇮", "code": "FI", "dial_code": "+358"},
  "fr": {"@type": "languageCodeDataDetail", "name": "France", "flag": "🇫🇷", "code": "FR", "dial_code": "+33"},
  "gf": {"@type": "languageCodeDataDetail", "name": "French Guiana", "flag": "🇬🇫", "code": "GF", "dial_code": "+594"},
  "pf": {"@type": "languageCodeDataDetail", "name": "French Polynesia", "flag": "🇵🇫", "code": "PF", "dial_code": "+689"},
  "tf": {"@type": "languageCodeDataDetail", "name": "French Southern Territories", "flag": "🇹🇫", "code": "TF", "dial_code": "+262"},
  "ga": {"@type": "languageCodeDataDetail", "name": "Gabon", "flag": "🇬🇦", "code": "GA", "dial_code": "+241"},
  "gm": {"@type": "languageCodeDataDetail", "name": "Gambia", "flag": "🇬🇲", "code": "GM", "dial_code": "+220"},
  "ge": {"@type": "languageCodeDataDetail", "name": "Georgia", "flag": "🇬🇪", "code": "GE", "dial_code": "+995"},
  "de": {"@type": "languageCodeDataDetail", "name": "Germany", "flag": "🇩🇪", "code": "DE", "dial_code": "+49"},
  "gh": {"@type": "languageCodeDataDetail", "name": "Ghana", "flag": "🇬🇭", "code": "GH", "dial_code": "+233"},
  "gi": {"@type": "languageCodeDataDetail", "name": "Gibraltar", "flag": "🇬🇮", "code": "GI", "dial_code": "+350"},
  "gr": {"@type": "languageCodeDataDetail", "name": "Greece", "flag": "🇬🇷", "code": "GR", "dial_code": "+30"},
  "gl": {"@type": "languageCodeDataDetail", "name": "Greenland", "flag": "🇬🇱", "code": "GL", "dial_code": "+299"},
  "gd": {"@type": "languageCodeDataDetail", "name": "Grenada", "flag": "🇬🇩", "code": "GD", "dial_code": "+1473"},
  "gp": {"@type": "languageCodeDataDetail", "name": "Guadeloupe", "flag": "🇬🇵", "code": "GP", "dial_code": "+590"},
  "gu": {"@type": "languageCodeDataDetail", "name": "Guam", "flag": "🇬🇺", "code": "GU", "dial_code": "+1671"},
  "gt": {"@type": "languageCodeDataDetail", "name": "Guatemala", "flag": "🇬🇹", "code": "GT", "dial_code": "+502"},
  "gg": {"@type": "languageCodeDataDetail", "name": "Guernsey", "flag": "🇬🇬", "code": "GG", "dial_code": "+44"},
  "gn": {"@type": "languageCodeDataDetail", "name": "Guinea", "flag": "🇬🇳", "code": "GN", "dial_code": "+224"},
  "gw": {"@type": "languageCodeDataDetail", "name": "Guinea-Bissau", "flag": "🇬🇼", "code": "GW", "dial_code": "+245"},
  "gy": {"@type": "languageCodeDataDetail", "name": "Guyana", "flag": "🇬🇾", "code": "GY", "dial_code": "+592"},
  "ht": {"@type": "languageCodeDataDetail", "name": "Haiti", "flag": "🇭🇹", "code": "HT", "dial_code": "+509"},
  "hm": {"@type": "languageCodeDataDetail", "name": "Heard Island and Mcdonald Islands", "flag": "🇭🇲", "code": "HM", "dial_code": "+672"},
  "va": {"@type": "languageCodeDataDetail", "name": "Holy See (Vatican City State)", "flag": "🇻🇦", "code": "VA", "dial_code": "+379"},
  "hn": {"@type": "languageCodeDataDetail", "name": "Honduras", "flag": "🇭🇳", "code": "HN", "dial_code": "+504"},
  "hk": {"@type": "languageCodeDataDetail", "name": "Hong Kong", "flag": "🇭🇰", "code": "HK", "dial_code": "+852"},
  "hu": {"@type": "languageCodeDataDetail", "name": "Hungary", "flag": "🇭🇺", "code": "HU", "dial_code": "+36"},
  "is": {"@type": "languageCodeDataDetail", "name": "Iceland", "flag": "🇮🇸", "code": "IS", "dial_code": "+354"},
  "in": {"@type": "languageCodeDataDetail", "name": "India", "flag": "🇮🇳", "code": "IN", "dial_code": "+91"},
  "id": {"@type": "languageCodeDataDetail", "name": "Indonesia", "flag": "🇮🇩", "code": "ID", "dial_code": "+62"},
  "ir": {"@type": "languageCodeDataDetail", "name": "Iran, Islamic Republic of Persian Gulf", "flag": "🇮🇷", "code": "IR", "dial_code": "+98"},
  "iq": {"@type": "languageCodeDataDetail", "name": "Iraq", "flag": "🇮🇶", "code": "IQ", "dial_code": "+964"},
  "ie": {"@type": "languageCodeDataDetail", "name": "Ireland", "flag": "🇮🇪", "code": "IE", "dial_code": "+353"},
  "im": {"@type": "languageCodeDataDetail", "name": "Isle of Man", "flag": "🇮🇲", "code": "IM", "dial_code": "+44"},
  "il": {"@type": "languageCodeDataDetail", "name": "Israel", "flag": "🇮🇱", "code": "IL", "dial_code": "+972"},
  "it": {"@type": "languageCodeDataDetail", "name": "Italy", "flag": "🇮🇹", "code": "IT", "dial_code": "+39"},
  "jm": {"@type": "languageCodeDataDetail", "name": "Jamaica", "flag": "🇯🇲", "code": "JM", "dial_code": "+1876"},
  "jp": {"@type": "languageCodeDataDetail", "name": "Japan", "flag": "🇯🇵", "code": "JP", "dial_code": "+81"},
  "je": {"@type": "languageCodeDataDetail", "name": "Jersey", "flag": "🇯🇪", "code": "JE", "dial_code": "+44"},
  "jo": {"@type": "languageCodeDataDetail", "name": "Jordan", "flag": "🇯🇴", "code": "JO", "dial_code": "+962"},
  "kz": {"@type": "languageCodeDataDetail", "name": "Kazakhstan", "flag": "🇰🇿", "code": "KZ", "dial_code": "+7"},
  "ke": {"@type": "languageCodeDataDetail", "name": "Kenya", "flag": "🇰🇪", "code": "KE", "dial_code": "+254"},
  "ki": {"@type": "languageCodeDataDetail", "name": "Kiribati", "flag": "🇰🇮", "code": "KI", "dial_code": "+686"},
  "kp": {"@type": "languageCodeDataDetail", "name": "Korea, Democratic People's Republic of Korea", "flag": "🇰🇵", "code": "KP", "dial_code": "+850"},
  "ko": {"@type": "languageCodeDataDetail", "name": "Korea, Republic of South Korea", "flag": "🇰🇷", "code": "KO", "dial_code": "+82"},
  "xk": {"@type": "languageCodeDataDetail", "name": "Kosovo", "flag": "🇽🇰", "code": "XK", "dial_code": "+383"},
  "kw": {"@type": "languageCodeDataDetail", "name": "Kuwait", "flag": "🇰🇼", "code": "KW", "dial_code": "+965"},
  "kg": {"@type": "languageCodeDataDetail", "name": "Kyrgyzstan", "flag": "🇰🇬", "code": "KG", "dial_code": "+996"},
  "la": {"@type": "languageCodeDataDetail", "name": "Laos", "flag": "🇱🇦", "code": "LA", "dial_code": "+856"},
  "lv": {"@type": "languageCodeDataDetail", "name": "Latvia", "flag": "🇱🇻", "code": "LV", "dial_code": "+371"},
  "lb": {"@type": "languageCodeDataDetail", "name": "Lebanon", "flag": "🇱🇧", "code": "LB", "dial_code": "+961"},
  "ls": {"@type": "languageCodeDataDetail", "name": "Lesotho", "flag": "🇱🇸", "code": "LS", "dial_code": "+266"},
  "lr": {"@type": "languageCodeDataDetail", "name": "Liberia", "flag": "🇱🇷", "code": "LR", "dial_code": "+231"},
  "ly": {"@type": "languageCodeDataDetail", "name": "Libyan Arab Jamahiriya", "flag": "🇱🇾", "code": "LY", "dial_code": "+218"},
  "li": {"@type": "languageCodeDataDetail", "name": "Liechtenstein", "flag": "🇱🇮", "code": "LI", "dial_code": "+423"},
  "lt": {"@type": "languageCodeDataDetail", "name": "Lithuania", "flag": "🇱🇹", "code": "LT", "dial_code": "+370"},
  "lu": {"@type": "languageCodeDataDetail", "name": "Luxembourg", "flag": "🇱🇺", "code": "LU", "dial_code": "+352"},
  "mo": {"@type": "languageCodeDataDetail", "name": "Macao", "flag": "🇲🇴", "code": "MO", "dial_code": "+853"},
  "mk": {"@type": "languageCodeDataDetail", "name": "Macedonia", "flag": "🇲🇰", "code": "MK", "dial_code": "+389"},
  "mg": {"@type": "languageCodeDataDetail", "name": "Madagascar", "flag": "🇲🇬", "code": "MG", "dial_code": "+261"},
  "mw": {"@type": "languageCodeDataDetail", "name": "Malawi", "flag": "🇲🇼", "code": "MW", "dial_code": "+265"},
  "my": {"@type": "languageCodeDataDetail", "name": "Malaysia", "flag": "🇲🇾", "code": "MY", "dial_code": "+60"},
  "mv": {"@type": "languageCodeDataDetail", "name": "Maldives", "flag": "🇲🇻", "code": "MV", "dial_code": "+960"},
  "ml": {"@type": "languageCodeDataDetail", "name": "Mali", "flag": "🇲🇱", "code": "ML", "dial_code": "+223"},
  "mt": {"@type": "languageCodeDataDetail", "name": "Malta", "flag": "🇲🇹", "code": "MT", "dial_code": "+356"},
  "mh": {"@type": "languageCodeDataDetail", "name": "Marshall Islands", "flag": "🇲🇭", "code": "MH", "dial_code": "+692"},
  "mq": {"@type": "languageCodeDataDetail", "name": "Martinique", "flag": "🇲🇶", "code": "MQ", "dial_code": "+596"},
  "mr": {"@type": "languageCodeDataDetail", "name": "Mauritania", "flag": "🇲🇷", "code": "MR", "dial_code": "+222"},
  "mu": {"@type": "languageCodeDataDetail", "name": "Mauritius", "flag": "🇲🇺", "code": "MU", "dial_code": "+230"},
  "yt": {"@type": "languageCodeDataDetail", "name": "Mayotte", "flag": "🇾🇹", "code": "YT", "dial_code": "+262"},
  "mx": {"@type": "languageCodeDataDetail", "name": "Mexico", "flag": "🇲🇽", "code": "MX", "dial_code": "+52"},
  "fm": {"@type": "languageCodeDataDetail", "name": "Micronesia, Federated States of Micronesia", "flag": "🇫🇲", "code": "FM", "dial_code": "+691"},
  "md": {"@type": "languageCodeDataDetail", "name": "Moldova", "flag": "🇲🇩", "code": "MD", "dial_code": "+373"},
  "mc": {"@type": "languageCodeDataDetail", "name": "Monaco", "flag": "🇲🇨", "code": "MC", "dial_code": "+377"},
  "mn": {"@type": "languageCodeDataDetail", "name": "Mongolia", "flag": "🇲🇳", "code": "MN", "dial_code": "+976"},
  "me": {"@type": "languageCodeDataDetail", "name": "Montenegro", "flag": "🇲🇪", "code": "ME", "dial_code": "+382"},
  "ms": {"@type": "languageCodeDataDetail", "name": "Montserrat", "flag": "🇲🇸", "code": "MS", "dial_code": "+1664"},
  "ma": {"@type": "languageCodeDataDetail", "name": "Morocco", "flag": "🇲🇦", "code": "MA", "dial_code": "+212"},
  "mz": {"@type": "languageCodeDataDetail", "name": "Mozambique", "flag": "🇲🇿", "code": "MZ", "dial_code": "+258"},
  "mm": {"@type": "languageCodeDataDetail", "name": "Myanmar", "flag": "🇲🇲", "code": "MM", "dial_code": "+95"},
  "na": {"@type": "languageCodeDataDetail", "name": "Namibia", "flag": "🇳🇦", "code": "NA", "dial_code": "+264"},
  "nr": {"@type": "languageCodeDataDetail", "name": "Nauru", "flag": "🇳🇷", "code": "NR", "dial_code": "+674"},
  "np": {"@type": "languageCodeDataDetail", "name": "Nepal", "flag": "🇳🇵", "code": "NP", "dial_code": "+977"},
  "nl": {"@type": "languageCodeDataDetail", "name": "Netherlands", "flag": "🇳🇱", "code": "NL", "dial_code": "+31"},
  "an": {"@type": "languageCodeDataDetail", "name": "Netherlands Antilles", "flag": "", "code": "AN", "dial_code": "+599"},
  "nc": {"@type": "languageCodeDataDetail", "name": "New Caledonia", "flag": "🇳🇨", "code": "NC", "dial_code": "+687"},
  "nz": {"@type": "languageCodeDataDetail", "name": "New Zealand", "flag": "🇳🇿", "code": "NZ", "dial_code": "+64"},
  "ni": {"@type": "languageCodeDataDetail", "name": "Nicaragua", "flag": "🇳🇮", "code": "NI", "dial_code": "+505"},
  "ne": {"@type": "languageCodeDataDetail", "name": "Niger", "flag": "🇳🇪", "code": "NE", "dial_code": "+227"},
  "ng": {"@type": "languageCodeDataDetail", "name": "Nigeria", "flag": "🇳🇬", "code": "NG", "dial_code": "+234"},
  "nu": {"@type": "languageCodeDataDetail", "name": "Niue", "flag": "🇳🇺", "code": "NU", "dial_code": "+683"},
  "nf": {"@type": "languageCodeDataDetail", "name": "Norfolk Island", "flag": "🇳🇫", "code": "NF", "dial_code": "+672"},
  "mp": {"@type": "languageCodeDataDetail", "name": "Northern Mariana Islands", "flag": "🇲🇵", "code": "MP", "dial_code": "+1670"},
  "no": {"@type": "languageCodeDataDetail", "name": "Norway", "flag": "🇳🇴", "code": "NO", "dial_code": "+47"},
  "om": {"@type": "languageCodeDataDetail", "name": "Oman", "flag": "🇴🇲", "code": "OM", "dial_code": "+968"},
  "pk": {"@type": "languageCodeDataDetail", "name": "Pakistan", "flag": "🇵🇰", "code": "PK", "dial_code": "+92"},
  "pw": {"@type": "languageCodeDataDetail", "name": "Palau", "flag": "🇵🇼", "code": "PW", "dial_code": "+680"},
  "ps": {"@type": "languageCodeDataDetail", "name": "Palestinian Territory, Occupied", "flag": "🇵🇸", "code": "PS", "dial_code": "+970"},
  "pa": {"@type": "languageCodeDataDetail", "name": "Panama", "flag": "🇵🇦", "code": "PA", "dial_code": "+507"},
  "pg": {"@type": "languageCodeDataDetail", "name": "Papua New Guinea", "flag": "🇵🇬", "code": "PG", "dial_code": "+675"},
  "py": {"@type": "languageCodeDataDetail", "name": "Paraguay", "flag": "🇵🇾", "code": "PY", "dial_code": "+595"},
  "pe": {"@type": "languageCodeDataDetail", "name": "Peru", "flag": "🇵🇪", "code": "PE", "dial_code": "+51"},
  "ph": {"@type": "languageCodeDataDetail", "name": "Philippines", "flag": "🇵🇭", "code": "PH", "dial_code": "+63"},
  "pn": {"@type": "languageCodeDataDetail", "name": "Pitcairn", "flag": "🇵🇳", "code": "PN", "dial_code": "+64"},
  "pl": {"@type": "languageCodeDataDetail", "name": "Poland", "flag": "🇵🇱", "code": "PL", "dial_code": "+48"},
  "pt": {"@type": "languageCodeDataDetail", "name": "Portugal", "flag": "🇵🇹", "code": "PT", "dial_code": "+351"},
  "pr": {"@type": "languageCodeDataDetail", "name": "Puerto Rico", "flag": "🇵🇷", "code": "PR", "dial_code": "+1939"},
  "qa": {"@type": "languageCodeDataDetail", "name": "Qatar", "flag": "🇶🇦", "code": "QA", "dial_code": "+974"},
  "ro": {"@type": "languageCodeDataDetail", "name": "Romania", "flag": "🇷🇴", "code": "RO", "dial_code": "+40"},
  "ru": {"@type": "languageCodeDataDetail", "name": "Russia", "flag": "🇷🇺", "code": "RU", "dial_code": "+7"},
  "rw": {"@type": "languageCodeDataDetail", "name": "Rwanda", "flag": "🇷🇼", "code": "RW", "dial_code": "+250"},
  "re": {"@type": "languageCodeDataDetail", "name": "Reunion", "flag": "🇷🇪", "code": "RE", "dial_code": "+262"},
  "bl": {"@type": "languageCodeDataDetail", "name": "Saint Barthelemy", "flag": "🇧🇱", "code": "BL", "dial_code": "+590"},
  "sh": {"@type": "languageCodeDataDetail", "name": "Saint Helena, Ascension and Tristan Da Cunha", "flag": "🇸🇭", "code": "SH", "dial_code": "+290"},
  "kn": {"@type": "languageCodeDataDetail", "name": "Saint Kitts and Nevis", "flag": "🇰🇳", "code": "KN", "dial_code": "+1869"},
  "lc": {"@type": "languageCodeDataDetail", "name": "Saint Lucia", "flag": "🇱🇨", "code": "LC", "dial_code": "+1758"},
  "mf": {"@type": "languageCodeDataDetail", "name": "Saint Martin", "flag": "🇲🇫", "code": "MF", "dial_code": "+590"},
  "pm": {"@type": "languageCodeDataDetail", "name": "Saint Pierre and Miquelon", "flag": "🇵🇲", "code": "PM", "dial_code": "+508"},
  "vc": {"@type": "languageCodeDataDetail", "name": "Saint Vincent and the Grenadines", "flag": "🇻🇨", "code": "VC", "dial_code": "+1784"},
  "ws": {"@type": "languageCodeDataDetail", "name": "Samoa", "flag": "🇼🇸", "code": "WS", "dial_code": "+685"},
  "sm": {"@type": "languageCodeDataDetail", "name": "San Marino", "flag": "🇸🇲", "code": "SM", "dial_code": "+378"},
  "st": {"@type": "languageCodeDataDetail", "name": "Sao Tome and Principe", "flag": "🇸🇹", "code": "ST", "dial_code": "+239"},
  "sa": {"@type": "languageCodeDataDetail", "name": "Saudi Arabia", "flag": "🇸🇦", "code": "SA", "dial_code": "+966"},
  "sn": {"@type": "languageCodeDataDetail", "name": "Senegal", "flag": "🇸🇳", "code": "SN", "dial_code": "+221"},
  "rs": {"@type": "languageCodeDataDetail", "name": "Serbia", "flag": "🇷🇸", "code": "RS", "dial_code": "+381"},
  "sc": {"@type": "languageCodeDataDetail", "name": "Seychelles", "flag": "🇸🇨", "code": "SC", "dial_code": "+248"},
  "sl": {"@type": "languageCodeDataDetail", "name": "Sierra Leone", "flag": "🇸🇱", "code": "SL", "dial_code": "+232"},
  "sg": {"@type": "languageCodeDataDetail", "name": "Singapore", "flag": "🇸🇬", "code": "SG", "dial_code": "+65"},
  "sk": {"@type": "languageCodeDataDetail", "name": "Slovakia", "flag": "🇸🇰", "code": "SK", "dial_code": "+421"},
  "si": {"@type": "languageCodeDataDetail", "name": "Slovenia", "flag": "🇸🇮", "code": "SI", "dial_code": "+386"},
  "sb": {"@type": "languageCodeDataDetail", "name": "Solomon Islands", "flag": "🇸🇧", "code": "SB", "dial_code": "+677"},
  "so": {"@type": "languageCodeDataDetail", "name": "Somalia", "flag": "🇸🇴", "code": "SO", "dial_code": "+252"},
  "za": {"@type": "languageCodeDataDetail", "name": "South Africa", "flag": "🇿🇦", "code": "ZA", "dial_code": "+27"},
  "ss": {"@type": "languageCodeDataDetail", "name": "South Sudan", "flag": "🇸🇸", "code": "SS", "dial_code": "+211"},
  "gs": {"@type": "languageCodeDataDetail", "name": "South Georgia and the South Sandwich Islands", "flag": "🇬🇸", "code": "GS", "dial_code": "+500"},
  "es": {"@type": "languageCodeDataDetail", "name": "Spain", "flag": "🇪🇸", "code": "ES", "dial_code": "+34"},
  "lk": {"@type": "languageCodeDataDetail", "name": "Sri Lanka", "flag": "🇱🇰", "code": "LK", "dial_code": "+94"},
  "sd": {"@type": "languageCodeDataDetail", "name": "Sudan", "flag": "🇸🇩", "code": "SD", "dial_code": "+249"},
  "sr": {"@type": "languageCodeDataDetail", "name": "Suriname", "flag": "🇸🇷", "code": "SR", "dial_code": "+597"},
  "sj": {"@type": "languageCodeDataDetail", "name": "Svalbard and Jan Mayen", "flag": "🇸🇯", "code": "SJ", "dial_code": "+47"},
  "sz": {"@type": "languageCodeDataDetail", "name": "Swaziland", "flag": "🇸🇿", "code": "SZ", "dial_code": "+268"},
  "se": {"@type": "languageCodeDataDetail", "name": "Sweden", "flag": "🇸🇪", "code": "SE", "dial_code": "+46"},
  "ch": {"@type": "languageCodeDataDetail", "name": "Switzerland", "flag": "🇨🇭", "code": "CH", "dial_code": "+41"},
  "sy": {"@type": "languageCodeDataDetail", "name": "Syrian Arab Republic", "flag": "🇸🇾", "code": "SY", "dial_code": "+963"},
  "tw": {"@type": "languageCodeDataDetail", "name": "Taiwan", "flag": "🇹🇼", "code": "TW", "dial_code": "+886"},
  "tj": {"@type": "languageCodeDataDetail", "name": "Tajikistan", "flag": "🇹🇯", "code": "TJ", "dial_code": "+992"},
  "tz": {"@type": "languageCodeDataDetail", "name": "Tanzania, United Republic of Tanzania", "flag": "🇹🇿", "code": "TZ", "dial_code": "+255"},
  "th": {"@type": "languageCodeDataDetail", "name": "Thailand", "flag": "🇹🇭", "code": "TH", "dial_code": "+66"},
  "tl": {"@type": "languageCodeDataDetail", "name": "Timor-Leste", "flag": "🇹🇱", "code": "TL", "dial_code": "+670"},
  "tg": {"@type": "languageCodeDataDetail", "name": "Togo", "flag": "🇹🇬", "code": "TG", "dial_code": "+228"},
  "tk": {"@type": "languageCodeDataDetail", "name": "Tokelau", "flag": "🇹🇰", "code": "TK", "dial_code": "+690"},
  "to": {"@type": "languageCodeDataDetail", "name": "Tonga", "flag": "🇹🇴", "code": "TO", "dial_code": "+676"},
  "tt": {"@type": "languageCodeDataDetail", "name": "Trinidad and Tobago", "flag": "🇹🇹", "code": "TT", "dial_code": "+1868"},
  "tn": {"@type": "languageCodeDataDetail", "name": "Tunisia", "flag": "🇹🇳", "code": "TN", "dial_code": "+216"},
  "tr": {"@type": "languageCodeDataDetail", "name": "Turkey", "flag": "🇹🇷", "code": "TR", "dial_code": "+90"},
  "tm": {"@type": "languageCodeDataDetail", "name": "Turkmenistan", "flag": "🇹🇲", "code": "TM", "dial_code": "+993"},
  "tc": {"@type": "languageCodeDataDetail", "name": "Turks and Caicos Islands", "flag": "🇹🇨", "code": "TC", "dial_code": "+1649"},
  "tv": {"@type": "languageCodeDataDetail", "name": "Tuvalu", "flag": "🇹🇻", "code": "TV", "dial_code": "+688"},
  "ug": {"@type": "languageCodeDataDetail", "name": "Uganda", "flag": "🇺🇬", "code": "UG", "dial_code": "+256"},
  "ua": {"@type": "languageCodeDataDetail", "name": "Ukraine", "flag": "🇺🇦", "code": "UA", "dial_code": "+380"},
  "ae": {"@type": "languageCodeDataDetail", "name": "United Arab Emirates", "flag": "🇦🇪", "code": "AE", "dial_code": "+971"},
  "gb": {"@type": "languageCodeDataDetail", "name": "United Kingdom", "flag": "🇬🇧", "code": "GB", "dial_code": "+44"},
  "us": {"@type": "languageCodeDataDetail", "name": "United States", "flag": "🇺🇸", "code": "US", "dial_code": "+1"},
  "uy": {"@type": "languageCodeDataDetail", "name": "Uruguay", "flag": "🇺🇾", "code": "UY", "dial_code": "+598"},
  "uz": {"@type": "languageCodeDataDetail", "name": "Uzbekistan", "flag": "🇺🇿", "code": "UZ", "dial_code": "+998"},
  "vu": {"@type": "languageCodeDataDetail", "name": "Vanuatu", "flag": "🇻🇺", "code": "VU", "dial_code": "+678"},
  "ve": {"@type": "languageCodeDataDetail", "name": "Venezuela, Bolivarian Republic of Venezuela", "flag": "🇻🇪", "code": "VE", "dial_code": "+58"},
  "vn": {"@type": "languageCodeDataDetail", "name": "Vietnam", "flag": "🇻🇳", "code": "VN", "dial_code": "+84"},
  "vg": {"@type": "languageCodeDataDetail", "name": "Virgin Islands, British", "flag": "🇻🇬", "code": "VG", "dial_code": "+1284"},
  "vi": {"@type": "languageCodeDataDetail", "name": "Virgin Islands, U.S.", "flag": "🇻🇮", "code": "VI", "dial_code": "+1340"},
  "wf": {"@type": "languageCodeDataDetail", "name": "Wallis and Futuna", "flag": "🇼🇫", "code": "WF", "dial_code": "+681"},
  "ye": {"@type": "languageCodeDataDetail", "name": "Yemen", "flag": "🇾🇪", "code": "YE", "dial_code": "+967"},
  "zm": {"@type": "languageCodeDataDetail", "name": "Zambia", "flag": "🇿🇲", "code": "ZM", "dial_code": "+260"},
  "zw": {"@type": "languageCodeDataDetail", "name": "Zimbabwe", "flag": "🇿🇼", "code": "ZW", "dial_code": "+263"}
};
